---
- name: Add jenkins user
  hosts: jenkins
  jenkins_users:
  - username: 'temp'
    full_name: 'Temp'
    email: 'temp@temp.com'
    password: 'temp'
    roles: 
     - 'jenkins-administer'
    public_keys: []
