---
- hosts: jenkins
  become: true
  tasks:
  - name: Creating jenkins user
    jenkins_users:
    - username: 'temp'
      full_name: 'Temp'
      email: 'temp@temp.com'
      password: 'temp'
      roles: 
       - 'jenkins-administer'
      public_keys: []
