---
- hosts: sonar
  become: true
  tasks:
  - name: Install wget
    apt:
      name: wget
      state: present

  - name: Install openjdk
    apt:
      name: default-jdk
      state: present
  - name: create sonar user
    shell:
      command: adduser --system --no-create-home --group --disabled-login sonarqube

